Socket chat
sawyre/socket_chat pull request #1
Opened 2023-10-09 10:01 UTC by sawyre

Здравствуйте,
Для запуска сервера нужно ввести:
python server.py
Для запуска клиента:
python client.py
Заранее спасибо за проверку.

2023-10-10 09:00 UTC, aleksandr-semenov-dbp requested changes

2023-10-10 09:00 UTC, aleksandr-semenov-dbp commented on client.py
> +        output_thread.join()
В результате получилось 3 потока - один на отправку, один на прием и третий довольно бесполезный который ждет тех двух. Можно get_messages() просто вызвать в основном потоке и обойтись двумя

2023-10-10 09:00 UTC, aleksandr-semenov-dbp commented on client.py
> +            for message in messages:
for author, message in messages: ?

2023-10-10 09:00 UTC, aleksandr-semenov-dbp commented on client.py
> +        inp = input(LOGIN + ": ")
лучше использовать f-string чем форматировать строчку плюсами

2023-10-10 09:00 UTC, aleksandr-semenov-dbp commented on client.py
> +LOGIN = ""
по соглашению, в питоне апперкейс - это константы, глобальные переменные пишутся как и обычные, не стоит путать читающих

2023-10-10 09:00 UTC, aleksandr-semenov-dbp commented on models/chat.py
> +    messages: t.List[t.Tuple["User", str]] = []
В более-менее современном питоне для тайпхинтов используются просто set/list/tuple, если питон старый можно оставить так, но переименовывать модули (typing -> t) не приветствуется, за исключением некоторых особенных (pandas, numpy), `from typing import TYPE_CHECKING` не так уж и громоздко смотрится

2023-10-10 09:00 UTC, aleksandr-semenov-dbp commented on server.py
> +                logging.error(
logging.exception() лучше покажет иксепшн

2023-10-10 09:00 UTC, aleksandr-semenov-dbp commented on server.py
> +def start_chat(connection: socket.socket) -> None:
не очень хороший нейминг, как будто слово start нерелевантно, здесь не старт, здесь весь чат

2023-10-10 09:00 UTC, aleksandr-semenov-dbp commented on server.py
> +                bytes(json.dumps([(sender.name, message)]), "UTF-8")
Т.е. всегда отправляется список из одного элемента, какой в этом смысл?

2023-10-10 09:00 UTC, aleksandr-semenov-dbp commented on server.py
> +        time.sleep(1)
это породит жуткие тормоза сервера

2023-10-10 09:00 UTC, aleksandr-semenov-dbp commented on server.py
> +                name=bytes.decode(name, "UTF-8"),
второй раз decode()

2023-10-10 09:00 UTC, aleksandr-semenov-dbp commented on client.py
> +                file.flush()
Надо бы и на экран что-то вывести?

2023-10-10 09:00 UTC, aleksandr-semenov-dbp commented on client.py
> +            messages = json.loads(data)
при парсинге данных приходящих извне всегда надо проверять не произошло ли ошибки

2023-10-10 10:54 UTC, sawyre commented on client.py
> +        output_thread.join()
Поправил, спасибо!

2023-10-10 10:54 UTC, sawyre commented on client.py
> +            for message in messages:
Поправил, спасибо!

2023-10-10 10:54 UTC, sawyre commented on client.py
> +        inp = input(LOGIN + ": ")
Поправил, спасибо!

2023-10-10 10:54 UTC, sawyre commented on client.py
> +LOGIN = ""
Поправил, спасибо!

2023-10-10 10:54 UTC, sawyre commented on models/chat.py
> +    messages: t.List[t.Tuple["User", str]] = []
Поправил, спасибо!

2023-10-10 10:55 UTC, sawyre commented on server.py
> +                logging.error(
Поправил, спасибо!

2023-10-10 10:58 UTC, sawyre commented on server.py
> +def start_chat(connection: socket.socket) -> None:
Хм, я тут наверно сам себе проблему создал, я просто назвал переменную глобальную chat и поэтому пришлось придумывать имя для функции другое, чтобы не было двух chat. Думал слегка усложнить структуру, и убрать chat в какой то класс с параметрами, но решил не перемудрять.
Переименновал в run_chat, часто видел такие функции, которые просто крутятся, мб так лучше

2023-10-10 10:59 UTC, sawyre commented on server.py
> +                bytes(json.dumps([(sender.name, message)]), "UTF-8")
Извиняюсь.
Это осталось от моих старых наработок и я решил не убирать, мало ли решу все таки пачками передавать собщения, а не по одному.) Убрал.

2023-10-10 10:59 UTC, sawyre commented on server.py
> +                name=bytes.decode(name, "UTF-8"),
Поправил, спасибо!

2023-10-30 18:06 UTC, sawyre commented on server.py
> +        time.sleep(1)
Спасибо, убрал.

2023-10-30 18:09 UTC, sawyre commented on client.py
> +                file.flush()
Долго с этим возился, не придумал, как это сделать человечески, без использования GUI:
Есть проблема: если начать печатать, потом получить сообщение, оно отобразится после того, что печатает пользователь. И я пытался это делать через print, input кажется блокирует print, но не блокирует logger, в итоге сделал отображение через логгер. Хотя так же оставил отображение в файлах.

2023-10-30 18:09 UTC, sawyre commented on client.py
> +            messages = json.loads(data)
Добавил проверку минимальную.

2023-11-03 08:55 UTC, aleksandr-semenov-dbp approved these changes

2024-03-01 19:15 UTC, merged